network:
  version: 2
  renderer: networkd
  ethernets:
    enp0s3:
      addresses:
        - 192.168.59.52/24
      gateway4: 192.168.59.51
      nameservers:
        addresses: [1.1.1.1, 8.8.8.8]

